quarkus:
  package:
    uber-jar: true
  http:
    cors: true
# Mailer config
  mailer:
    from: my-blog@mail.com
    host: ${MAIL_CLIENT}
    port: 25
    ssl: false
    mock: false
  ## Database settings
  datasource:
    driver: org.postgresql.Driver
    username: my_blog
    password: password
    url: jdbc:postgresql://${DB_SERVER}/my_blog
## Miscellanous
  banner:
    path: banner.txt
my-blog:
  directory: ${user.home}/my-blog
  server: http://${SERVER}
  front-uri: http://${FLUTTER_APP}